
[[datatypes]]
== Data types

In this document, the _float_ and _integer_ types denote Lua numbers, while other types
such as _boolean_, _string_, etc denote standard Lua types. Note that _float_
here just means 'floating point' as opposed to 'integer', and does not imply 
single-precision (all numbers are actually represented internally using double-precision).

Angles are always expressed in radians.

Vectors and quaternions are by default represented as Lua arrays containing
_float_ elements. The meaning of the elements thus depends on their position, as detailed below,
and there is no syntactic sugar such as _v.x_ and _v.y_ to access them (unless one enables <<glmath_compat, GLMATH compatibility>>).

* [[vec3]]
[small]#*vec3* = {_x_, _y_, _z_} +
All elements are floats. +
(Rfr: _ccd_vec3_t_)#

* [[quat]]
[small]#*quat* = {_w_ _x_, _y_, _z_} +
All elements are floats (note that the _w_ component is in the first position). +
(Rfr: _ccd_quat_t_)#


[[glmath_compat]]
== GLMATH compatibility

As an option, it is possible to instruct MoonCCD to return vectors and quaternions
as the corresponding https://github.com/stetre/moonglmath[MoonGLMATH] types, instead of returning them as plain tables (which is the default).
footnote:[MoonGLMATH types are convenient because they support operators and synctatic sugar, but I
chose not to impose their use because one may want to use an alternative math library, or none at all.]

(Notice that for function arguments nothing changes, since MoonGLMATH types are compatible
with the corresponding plain tables used by default, thus they can be used as function arguments in
any case).

Use the following functions to control GLMATH compatibility:

* *glmath_compat*(_boolean_) +
[small]#Enables/disables GLMATH compatibility (which by default is disabled). +
Enabling this functionality requires MoonGLMATH to be installed.#

* _boolean_ = *is_glmath_compat*( ) +
[small]#Returns _true_ if GLMATH compatibility is enabled.#

